create table public.contacts(
    id         integer generated by default as identityprimary key,
    first_name varchar(100) not null,
    last_name  varchar(100) not null,
    email      varchar(100) not null,
    phone      varchar(20)  not null
);

alter table public.contacts
    owner to postgres;