-- Создание таблицы Category
CREATE TABLE category
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO category (name) VALUES ('category1');
INSERT INTO category (name) VALUES ('category2');
INSERT INTO category (name) VALUES ('category3');
INSERT INTO category (name) VALUES ('category4');

-- Создание таблицы Book
CREATE TABLE book
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    author      VARCHAR(255) NOT NULL,
    category_id INTEGER,
    CONSTRAINT fk_category FOREIGN KEY (category_id)
        REFERENCES category (id)
        ON DELETE SET NULL
);